export const INPUTS_CONFIG = {
  name: {
    variant: "default",
    label: "Name",
    placeholder: "Enter your name",
    required: true,
    type: "text",
    size: "md",
    radius: "lg",
    description: "Enter description",
    error: "",
  },
  nickname: {
    variant: "default",
    label: "Nickname",
    placeholder: "Enter your nickname",
    required: true,
    type: "text",
    size: "md",
    radius: "lg",
    description: "Enter description",
    error: "",
  },
  email: {
    variant: "default",
    label: "Email",
    placeholder: "Enter your email",
    required: true,
    type: "email",
    size: "md",
    radius: "lg",
    description: "Enter description",
    error: "",
  },
  password: {
    variant: "default",
    label: "Password",
    placeholder: "Enter your password",
    required: true,
    type: "password",
    size: "md",
    radius: "lg",
    description: "Enter description",
    error: "",
  },
  confirmPassword: {
    variant: "default",
    label: "confirmPassword",
    placeholder: "Confirm password",
    required: true,
    type: "password",
    size: "md",
    radius: "lg",
    description: "Enter description",
    error: "",
  },
};
